"""Extract the the connecting bus timetable from the national GTFS feed into a small asset.

    py tools/build_bus_timetable.py path/to/gtfs-nl.zip

Writes assets/timetable.json.

Why a file rather than a live API: OVapi's live endpoints only accept numeric
the operator timing-point codes, and the bus stops we need are not reachable that way -
/stopareacode/, /tpc/ with an alphabetic code, and /line/ detail all return empty
objects. See BACKLOG. The GTFS feed has the whole timetable, so we take it once.

That is no real loss. You plan a departure against the *scheduled* time; live
delays matter when you are standing at the stop, not at your front door.

The feed is ~184MB and covers one term, so this needs re-running when it expires
- assets/timetable.json carries its own valid_to date and commute.py warns.
"""

from __future__ import annotations

import argparse
import collections
import csv
import io
import json
import sys
import zipfile
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from exitscreen import settings  # noqa: E402
OUT = ROOT / "assets" / "timetable.json"

# Which route and which two platforms - personal, so they come from the
# gitignored settings file. To find yours: search routes.txt for your line's
# short_name and your operator, then read a sample trip's stop_times to get the
# PHYSICAL platform ids. Matching on stop name alone finds a location_type=1
# parent area that appears in no stop_times row at all.
ROUTE_ID = settings.get("commute", "gtfs_route_id")
OUTBOUND = "0"
BOARD_STOP = settings.get("commute", "board_stop_id")
ALIGHT_STOP = settings.get("commute", "alight_stop_id")


def rows(z: zipfile.ZipFile, name: str):
    with z.open(name) as fh:
        yield from csv.DictReader(io.TextIOWrapper(fh, encoding="utf-8-sig"))


def build(gtfs: Path) -> dict:
    z = zipfile.ZipFile(gtfs)

    trips = {r["trip_id"]: r["service_id"] for r in rows(z, "trips.txt")
             if r["route_id"] == ROUTE_ID and r["direction_id"] == OUTBOUND}
    print(f"  {len(trips)} outbound trips")

    dep, arr = {}, {}
    print("  streaming stop_times (~859MB uncompressed) ...")
    for r in rows(z, "stop_times.txt"):
        t = r["trip_id"]
        if t not in trips:
            continue
        if r["stop_id"] == BOARD_STOP:
            dep[t] = r["departure_time"][:5]
        elif r["stop_id"] == ALIGHT_STOP:
            arr[t] = r["arrival_time"][:5]

    pairs = {t: (dep[t], arr[t]) for t in trips if t in dep and t in arr}
    print(f"  {len(pairs)} trips serve both stops")

    active = collections.defaultdict(set)
    for r in rows(z, "calendar_dates.txt"):
        if r["exception_type"] == "1":
            active[r["service_id"]].add(r["date"])

    by_date = collections.defaultdict(set)
    for trip, (d, a) in pairs.items():
        for ds in active.get(trips[trip], ()):
            by_date[ds].add((d, a))

    # Every service day turns out to carry an identical timetable, so store the
    # pattern once and list the dates it applies to. Keeps the asset tiny and
    # makes an odd day obvious rather than hidden in a wall of duplicates.
    patterns = collections.defaultdict(list)
    for ds, runs in by_date.items():
        patterns[tuple(sorted(runs))].append(ds)

    print(f"  {len(by_date)} service dates, {len(patterns)} distinct timetable(s)")
    dates = sorted(by_date)
    return {
        "_comment": "Generated by tools/build_bus_timetable.py - do not hand-edit.",
        "route": "the connecting service",
        "board": "the interchange (perron AA)",
        "alight": "the university stop",
        "valid_from": dates[0],
        "valid_to": dates[-1],
        "service_dates": dates,
        "timetables": [
            {"dates": sorted(ds), "runs": [list(r) for r in pattern]}
            for pattern, ds in patterns.items()
        ],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("gtfs", type=Path, help="path to gtfs-nl.zip")
    args = ap.parse_args()
    if not args.gtfs.exists():
        sys.exit(f"not found: {args.gtfs}\nGet it from http://gtfs.ovapi.nl/nl/gtfs-nl.zip")

    print(f"reading {args.gtfs} ({args.gtfs.stat().st_size / 1_048_576:.0f} MB)")
    data = build(args.gtfs)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=1), encoding="utf-8")

    first = data["timetables"][0]["runs"]
    print(f"\nwrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")
    print(f"  valid {data['valid_from']} .. {data['valid_to']}")
    print(f"  {len(first)} buses a day, {first[0][0]} -> {first[0][1]} "
          f"through {first[-1][0]} -> {first[-1][1]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
